# Generated by Django 4.1 on 2022-09-22 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='channel_name')),
            ],
        ),
        migrations.CreateModel(
            name='Notification_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, verbose_name='group_name')),
                ('description', models.TextField(max_length=255, verbose_name='description_ntf_group')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_names', models.CharField(max_length=255, verbose_name='service_name')),
                ('image', models.ImageField(blank=True, upload_to='media/%Y/%m/%d', verbose_name=' images')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='NTF_type_for_channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templates_for_massage', models.TextField(verbose_name='templates_for_massage')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='msg_sender.channel', verbose_name='channel')),
                ('ntf_group', models.ManyToManyField(blank=True, to='msg_sender.notification_group')),
            ],
        ),
        migrations.AddField(
            model_name='notification_group',
            name='service_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='msg_sender.service', verbose_name='service'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('status', models.CharField(max_length=30, verbose_name='Notification Status')),
                ('url', models.CharField(max_length=30, verbose_name='url')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created_at')),
                ('recipient', models.TextField(blank=True, null=True, verbose_name='employee_recipient')),
                ('ntf_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='msg_sender.notification_group', verbose_name='ntf_group')),
            ],
        ),
    ]
