# Generated by Django 4.1 on 2022-09-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(max_length=255, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification_group',
            name='description',
            field=models.TextField(max_length=255, verbose_name='description_ntf_group'),
        ),
    ]
