# Generated by Django 4.1 on 2022-09-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=255, verbose_name='description'),
        ),
    ]
