# Generated by Django 4.1 on 2022-09-07 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msg_sender', '0002_alter_notification_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='ntf_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='msg_sender.notification_group', verbose_name='ntf_group'),
        ),
        migrations.AlterField(
            model_name='ntf_type_for_channel',
            name='templates_for_massage',
            field=models.TextField(max_length=255, verbose_name='templates_for_massage'),
        ),
    ]
