# Generated by Django 4.1 on 2022-09-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_sender', '0003_alter_notification_ntf_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ntf_type_for_channel',
            name='channel',
        ),
        migrations.AddField(
            model_name='ntf_type_for_channel',
            name='channel',
            field=models.ManyToManyField(to='msg_sender.channel', verbose_name='channel'),
        ),
    ]
