# Generated by Django 4.1 on 2022-09-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_sender', '0005_alter_ntf_type_for_channel_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntf_type_for_channel',
            name='channel',
            field=models.ManyToManyField(blank=True, to='msg_sender.channel', verbose_name='channel'),
        ),
        migrations.AlterField(
            model_name='ntf_type_for_channel',
            name='ntf_group',
            field=models.ManyToManyField(blank=True, to='msg_sender.notification_group'),
        ),
        migrations.AlterField(
            model_name='ntf_type_for_channel',
            name='templates_for_massage',
            field=models.TextField(verbose_name='templates_for_massage'),
        ),
    ]
