# Generated by Django 4.1 on 2022-09-01 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('msg_sender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('receiver', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('send_to_email', models.BooleanField(default=True)),
                ('send_to_tg_channel', models.BooleanField(default=True)),
                ('send_to_tg_privet_channel', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empl_requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='адрес')),
                ('tg_nickname', models.CharField(max_length=50, null=True, verbose_name='tg_nickname')),
                ('tg_channel', models.CharField(max_length=50, null=True, verbose_name='tg_channel')),
                ('phone_number', models.CharField(max_length=50, null=True, verbose_name='tg_channel')),
                ('channel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='msg_sender.channel', verbose_name='employee')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='адрес')),
                ('channel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='msg_sender.channel', verbose_name='employee')),
                ('employee_requisites', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.empl_requisites', verbose_name='employee')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256, verbose_name='почта')),
                ('receiver', models.BooleanField(max_length=50, null=True, verbose_name='want_to_receive')),
                ('password', models.CharField(max_length=256, verbose_name='password')),
                ('repeat_password', models.CharField(max_length=256, verbose_name='repeat-password')),
                ('service', models.ManyToManyField(to='msg_sender.service')),
            ],
        ),
        migrations.AddField(
            model_name='empl_requisites',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.employee', verbose_name='employee'),
        ),
    ]
