# Generated by Django 4.1 on 2022-09-03 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('msg_sender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('receiver', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('channel', models.ManyToManyField(to='msg_sender.channel', verbose_name='channel_name')),
                ('service', models.ManyToManyField(to='msg_sender.service', verbose_name='service_name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empl_requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_nickname', models.CharField(max_length=50, null=True, verbose_name='tg_nickname')),
                ('tg_channel', models.CharField(max_length=50, null=True, verbose_name='tg_channel')),
                ('phone_number', models.CharField(max_length=50, null=True, verbose_name='phone_number')),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='employee')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='адрес')),
                ('channel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='msg_sender.channel', verbose_name='employee')),
                ('employee', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('employee_requisites', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.empl_requisites', verbose_name='employee')),
                ('service_name', models.ManyToManyField(to='msg_sender.service')),
            ],
        ),
    ]
