# Generated by Django 4.1 on 2022-09-07 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msg_sender', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='notification_group',
        ),
        migrations.AddField(
            model_name='myuser',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='msg_sender.channel', verbose_name='channel_name'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='notification_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='msg_sender.notification_group', verbose_name='notification_group'),
        ),
    ]
