# Generated by Django 4.1 on 2022-09-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_sender', '0002_alter_notification_ntf_group'),
        ('accounts', '0002_alter_myuser_channel_alter_myuser_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='employee_requisites',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.empl_requisites'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='service_name',
            field=models.ManyToManyField(blank=True, null=True, to='msg_sender.service'),
        ),
    ]
