# Generated by Django 4.1 on 2022-09-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_sender', '0003_alter_notification_ntf_group_and_more'),
        ('accounts', '0002_remove_myuser_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='notification_group',
        ),
        migrations.AddField(
            model_name='myuser',
            name='channel',
            field=models.ManyToManyField(to='msg_sender.channel', verbose_name='channel_name'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='notification_group',
            field=models.ManyToManyField(to='msg_sender.notification_group', verbose_name='notification_group'),
        ),
    ]
