# Generated by Django 4.1 on 2022-09-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_sender', '0002_alter_notification_ntf_group'),
        ('accounts', '0003_alter_subscription_employee_requisites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='employee_requisites',
            field=models.ManyToManyField(to='accounts.empl_requisites'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='service_name',
            field=models.ManyToManyField(to='msg_sender.service'),
        ),
    ]
