# Generated by Django 4.1 on 2022-09-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_result_requisites_empty_result_new_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='employee_requisites',
        ),
        migrations.AddField(
            model_name='subscription',
            name='employee_requisites',
            field=models.ManyToManyField(to='accounts.empl_requisites', verbose_name='employee_requisites for send'),
        ),
    ]
