# Generated by Django 4.1 on 2022-09-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_subscription_employee_requisites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='employee_requisites',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.empl_requisites'),
        ),
    ]
