# Generated by Django 4.1 on 2022-09-05 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msg_sender', '0002_alter_notification_ntf_group'),
        ('accounts', '0005_alter_subscription_employee_requisites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='service',
        ),
        migrations.AddField(
            model_name='myuser',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='msg_sender.channel', verbose_name='channel_name'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='msg_sender.service', verbose_name='service_name'),
        ),
    ]
