# Generated by Django 4.1 on 2022-09-05 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msg_sender', '0002_alter_notification_ntf_group'),
        ('accounts', '0006_remove_myuser_channel_remove_myuser_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empl_requisites',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='employee'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='msg_sender.channel', verbose_name='channel_name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='msg_sender.service', verbose_name='service_name'),
        ),
    ]
