# Generated by Django 4.1 on 2022-09-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_sender', '0002_alter_notification_ntf_group'),
        ('accounts', '0007_alter_empl_requisites_employee_alter_myuser_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='channel',
        ),
        migrations.AddField(
            model_name='subscription',
            name='channel',
            field=models.ManyToManyField(to='msg_sender.channel'),
        ),
    ]
