# Generated by Django 4.1 on 2022-09-05 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_subscription_channel_subscription_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='employee_requisites',
        ),
        migrations.AddField(
            model_name='subscription',
            name='employee_requisites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.empl_requisites', verbose_name='phone_number'),
        ),
    ]
