# Generated by Django 4.1 on 2022-09-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_subscription_employee_requisites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='employee_requisites',
        ),
        migrations.AddField(
            model_name='subscription',
            name='employee_requisites',
            field=models.ManyToManyField(to='accounts.empl_requisites'),
        ),
    ]
